sudo: false
language: python
python:
  - 3.5
install:
  pip install -r requirements.txt
script:
  - cd adventures
  - python manage.py makemigrations bucketlist
  - python manage.py migrate bucketlist
  - coverage run --omit=*env/* manage.py test
after_success:
  coveralls
notifications:
  email: false