# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucketlists',
            new_name='Bucketlist',
        ),
    ]
