# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_auto_20161121_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
